apiVersion: v1
kind: Service
metadata:
  name: headlamp-service
  namespace: headlamp
spec:
  type: LoadBalancer
  selector:
    name: headlamp
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP