apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-namespace-only
  namespace: argocd
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {} # Only allow communication from namespace