---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kubernetes-allow-only-argo-headlamp-monitoring
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  # ingress:
  # - from:
  #   - namespaceSelector:
  #       matchExpressions:
  #       - key: kubernetes.io/metadata.name
  #         operator: In
  #         values:
  #         values: ["argocd", "kube-system", "monitoring", "headlamp"]
  #   ports:
  #   - protocol: TCP
  #     port: 443
---