apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  project: default
  sources:
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno
      targetRevision: 3.6.1
      helm:
        values: |
          admissionController:
            replicas: 1
          webhookLabels:
            app.kubernetes.io/managed-by: argocd
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno-policies
      targetRevision: 2.1.0
      helm:
        values: |
          podSecurityStandard: restricted
          validationFailureAction: Audit
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true