apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno
      targetRevision: 3.2.0
      helm:
        values: |
          admissionController:
            replicas: 1

    # - repoURL: https://kyverno.github.io/kyverno/
    #   chart: kyverno-policies
    #   targetRevision: 3.2.0
    #   helm:
    #     values: |
    #       podSecurityStandard: restricted
    #       validationFailureAction: Audit
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - Replace=false