apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno
      targetRevision: 3.6.1
      helm:
        values: |
          admissionController:
            replicas: 1

    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno-policies
      targetRevision: 2.1.0
      helm:
        values: |
          podSecurityStandard: restricted
          validationFailureAction: Audit

    - repoURL: https://kyverno.github.io/policy-reporter
      chart: policy-reporter
      targetRevision: 3.7.0
      helm:
        values: |
          ui:
            enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true