apiVersion: v1
kind: Namespace
metadata:
  name: mc-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-server
  namespace: mc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-server
  template:
    metadata:
      labels:
        app: mc-server
    spec:
      containers:
      - name: minecraft
        image: docker.io/library/mc-server-manager:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "12Gi"
            cpu: "2"
          limits:
            memory: "14Gi"
        envFrom:
        - secretRef:
            name: mc-server-config
        ports:
        - containerPort: 25565
          name: mc-port
          protocol: TCP
        - containerPort: 24454
          name: voice-port
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: mc-server-service
  namespace: mc-server
spec:
  type: LoadBalancer 
  selector:
    app: mc-server 
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: 25565
    - name: voice
      protocol: UDP
      port: 24454
      targetPort: 24454