apiVersion: v1
kind: Namespace
metadata:
  name: mc-server
---
apiVersion: v1
kind: Service
metadata:
  name: mc-service
  namespace: mc-server
spec:
  type: LoadBalancer
  selector:
    app: mc-server
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
    - protocol: UDP
      port: 24454
      targetPort: 24454
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-server
  namespace: mc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-server
  template:
    metadata:
      labels:
        app: mc-server
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: minecraft
        image: docker.io/library/mc-server-manager:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "12Gi"
            cpu: "2"
          limits:
            memory: "14Gi"
        envFrom:
        - secretRef:
            name: mc-server-config
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
              drop:
                - ALL