apiVersion: v1
kind: Namespace
metadata:
  name: mc-server
---
apiVersion: v1
kind: Service
metadata:
  name: mc-service
  namespace: mc-server
spec:
  type: LoadBalancer
  selector:
    app: mc-server
  ports:
    - name: game
      protocol: TCP
      port: 25565
      targetPort: 25565
    - name: voice-chat
      protocol: UDP
      port: 24454
      targetPort: 24454
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow
  namespace: mc-server
spec:
  podSelector: 
    matchLabels:
      app: mc-server
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 25565 # Minecraft
    - protocol: UDP
      port: 24454 # Voice chat
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443 # For auth servers, look into using mesh network to restrict this more later
    - protocol: UDP
      port: 24454 # Voice chat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-server
  namespace: mc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-server
  template:
    metadata:
      labels:
        app: mc-server
    spec:
      containers:
      - name: minecraft
        image: docker.io/library/mc-server-manager:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            cpu: "8"
            memory: "12Gi"
        envFrom:
        - secretRef:
            name: mc-server-config
        volumeMounts:
        - name: mc-storage
          mountPath: /mc-storage
      volumes:
      - name: mc-storage
        persistentVolumeClaim:
          claimName: mc-storage-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-storage-pvc
  namespace: mc-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
# TO BE AWARE OF. The above is not fault tolerant, for that I would need to look into LongHorn for replicated storage (A NAS drive would have high latency for a game).