
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-secure-container-default
spec:
  admission: true
  background: true
  rules:
  - name: add-security-context
    match:
      resources:
        kinds:
        - Pod
    exclude:
      resources:
        namespaces:
        - kube-system
    mutate:
      patchStrategicMerge:
        spec:
          securityContext:
            runAsNonRoot: true
            +(runAsUser): 1000
            +(fsGroup): 1000
            +(runAsGroup): 1000
            seccompProfile:
              type: RuntimeDefault
          volumes:
          - name: "emptydir"
            emptyDir: {
              sizeLimit: "64Mi"
            }
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-secure-pod-default
spec:
  admission: true
  background: true
  rules:
  - name: add-security-context
    match:
      resources:
        kinds:
        - Pod
    exclude:
      resources:
        namespaces:
        - kube-system
    mutate:
      foreach:
      - list: "request.object.spec.[containers, initContainers, ephemeralContainers][] | []"
        patchStrategicMerge:
          spec:
            containers:
            - name: "{{ element.name }}"
              securityContext:
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  +(memory): "100Mi"
                  +(cpu): "100m"
                limits:
                  +(memory): "512Mi"
                  +(cpu): "500m"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: read-only-root-filesystem
spec:
  admission: true
  background: true
  rules:
  - name: add-security-context
    match:
      resources:
        kinds:
        - Pod
    exclude:
      resources:
        namespaces:
        - kube-system
        - monitoring
        - argocd
    mutate:
      foreach:
      - list: "request.object.spec.[containers, initContainers, ephemeralContainers][] | []"
        patchStrategicMerge:
          spec:
            containers:
            - name: "{{ element.name }}"
              securityContext:
                readOnlyRootFilesystem: true
              volumeMounts:
              - name: "emptydir"
                mountPath: /tmp
# ---
# apiVersion: kyverno.io/v1
# kind: ClusterPolicy
# metadata:
#   name: disable-automountserviceaccounttoken
#   annotations:
#     policies.kyverno.io/title: Disable automountServiceAccountToken
#     policies.kyverno.io/category: Other, EKS Best Practices
#     policies.kyverno.io/severity: medium
#     policies.kyverno.io/subject: ServiceAccount
#     kyverno.io/kyverno-version: 1.5.1
#     kyverno.io/kubernetes-version: "1.21"
#     policies.kyverno.io/description: >-
#       A new ServiceAccount called `default` is created whenever a new Namespace is created.
#       Pods spawned in that Namespace, unless otherwise set, will be assigned this ServiceAccount.
#       This policy mutates any new `default` ServiceAccounts to disable auto-mounting of the token
#       into Pods obviating the need to do so individually.      
# spec:
#   rules:
#   - name: disable-automountserviceaccounttoken
#     match:
#       resources:
#         kinds:
#         - ServiceAccount
#         names:
#         - default
#     exclude:
#       resources:
#         namespaces:
#         - kube-system
#         - argocd
#         - kyverno
#         - headlamp
#         - monitoring
#     mutate:
#       patchStrategicMerge:
#         automountServiceAccountToken: false
# ---
# apiVersion: kyverno.io/v1
# kind: ClusterPolicy
# metadata:
#   name: generate-default-deny
# spec:
#   generateExisting: true
#   admission: true
#   background: true
#   rules:
#   - name: default-intra-namespace-only-networking
#     match:
#       any:
#       - resources:
#           kinds:
#           - Namespace
#     exclude:
#       resources:
#         names:
#         - kube-system
#         - argocd
#         - kyverno
#         - monitoring
#         - headlamp
#     generate:
#       apiVersion: networking.k8s.io/v1
#       kind: NetworkPolicy
#       name: default-intra-namespace-only-networking
#       namespace: "{{request.object.metadata.name}}"
#       synchronize: true
#       data:
#         spec:
#           podSelector: {}
#           policyTypes:
#           - Ingress
#           - Egress
#           ingress:
#           - from:
#             - podSelector: {}
#           egress:
#           - to:
#             - podSelector: {}
#             - namespaceSelector: 
#                 matchLabels:
#                   kubernetes.io/metadata.name: kube-system
#               podSelector:
#                 matchLabels:
#                   k8s-app: kube-dns
#             ports:
#             - protocol: UDP
#               port: 53
#             - protocol: TCP
#               port: 53