
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-secure-container-default
spec:
  admission: true
  background: true
  rules:
  - name: add-security-context
    match:
      resources:
        kinds:
        - Pod
    exclude:
      resources:
        namespaces:
        - kube-system
    mutate:
      patchStrategicMerge:
        spec:
          securityContext:
            runAsNonRoot: true
            +(runAsUser): 1000
            +(fsGroup): 1000
            +(runAsGroup): 1000
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-secure-pod-default
spec:
  admission: true
  background: true
  rules:
  - name: add-security-context
    match:
      resources:
        kinds:
        - Pod
    exclude:
      resources:
        namespaces:
        - kube-system
    mutate:
      foreach:
      - list: "request.object.spec.[containers, initContainers, ephemeralContainers][] | []"
        patchStrategicMerge:
          spec:
            volumes:
              - name: "emptydir"
                emptyDir: 
                  sizeLimit: "64Mi"
            containers:
            - name: "{{ element.name }}"
              securityContext:
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  +(memory): "100Mi"
                  +(cpu): "100m"
                limits:
                  +(memory): "512Mi"
                  +(cpu): "500m"
              volumeMounts:
              - name: "emptydir"
                mountPath: /tmp
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disable-automount-service-token
spec:
  admission: true
  background: true
  rules:
  - name: add-security-context
    match:
      resources:
        kinds:
        - Pod
    exclude:
      resources:
        namespaces:
        - kube-system
        - argocd
        - kyverno
        - headlamp
        - monitoring
    mutate:
      patchStrategicMerge:
        spec:
          automountServiceAccountToken: false
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-default-deny
spec:
  generateExisting: true
  admission: true
  background: true
  rules:
  - name: default-intra-namespace-only-networking
    match:
      any:
      - resources:
          kinds:
          - Namespace
    exclude:
      resources:
        names:
        - kube-system
        - argocd
        - kyverno
        - monitoring
        - headlamp
    generate:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      name: default-intra-namespace-only-networking
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      data:
        spec:
          podSelector: {}
          policyTypes:
          - Ingress
          - Egress
          ingress:
          - from:
            - podSelector: {}
          egress:
          - to:
            - podSelector: {}
            - namespaceSelector: 
                matchLabels:
                  kubernetes.io/metadata.name: kube-system
              podSelector:
                matchLabels:
                  k8s-app: kube-dns
            ports:
            - protocol: UDP
              port: 53
            - protocol: TCP
              port: 53