
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-secure-container-default
spec:
  rules:
  - name: add-security-context
    match:
      resources:
        kinds:
        - Pod
    exclude:
      resources:
        namespaces:
        - kube-system
    mutate:
      patchStrategicMerge:
        spec:
          securityContext:
            runAsNonRoot: true
            +(runAsUser): 1000
            +(fsGroup): 1000
            +(runAsGroup): 1000
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-secure-pod-default
spec:
  rules:
  - name: add-security-context
    match:
      resources:
        kinds:
        - Pod
    exclude:
      resources:
        namespaces:
        - kube-system
    mutate:
      foreach:
      - list: "request.object.spec.[containers, initContainers, ephemeralContainers][] | []"
        patchStrategicMerge:
          spec:
            containers:
            - name: "{{ element.name }}"
              securityContext:
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  +(memory): "100Mi"
                  +(cpu): "100m"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disable-automount-service-token
spec:
  rules:
  - name: add-security-context
    match:
      resources:
        kinds:
        - Pod
    exclude:
      resources:
        namespaces:
        - kube-system
        - argocd
        - kyverno
        - headlamp
        - monitoring
    mutate:
      patchStrategicMerge:
        spec:
          automountServiceAccountToken: false
# TODO: Add network, resource policies. Exceptions for some namespaces
